"""
Django settings for CarmiSystem project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$8hqawp4-lctfc)0tlxv807mipv-!umc4!qke%!z8o(8u&6%uy"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["82.156.255.128"]

# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    # "django.contrib.auth",
    "django.contrib.contenttypes",
    # "django.contrib.sessions",
    # "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'drf_yasg',
    "rest_framework",
    'django_filters',
    "web.apps.WebConfig",
    'django_extensions',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CarmiSystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",
                # "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CarmiSystem.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    # myself
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "CarmiSysBases",
        "USER": "root",
        "PASSWORD": "yaung",
        # "HOST": "127.0.0.1",
        "HOST": "10.0.8.17",
        # "HOST": "82.156.255.128",
        "PORT": 3306,
    }
    # VMwareubuntu22.04
    # "default": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "CarmiSysBases",
    #     "USER": "root",
    #     "PASSWORD": "root123.",
    #     "HOST": "192.168.70.140",
    #     "PORT": 3306,
    # }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "zh-hans"

# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "/data/CarmiSystem_static/static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# redis的缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://127.0.0.1:6379/0",
        "LOCATION": "redis://10.0.8.17:6379/0",
        # "LOCATION": "redis://82.156.255.128:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "yaung"
        }
    }
}
"""
#####################Cors配置#####################

"""
# 布尔值默认False 如果为True 白名单不启用
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = ["https://127.0.0.1:5000"]
# 默认可以使用的非标准请求头，需要使用自定义请求头时，就可以进行修改
CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)
# 默认请求方法
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)
# 申请缓存options的时间，默认 86400s
CORS_PREFLIGHT_MAX_AGE = 86400
# 需要前端接受的特殊的请求头
CORS_EXPOSE_HEADERS = []
# 是否获取浏览器的cookie，布尔值，默认False
CORS_ALLOW_CREDENTIALS = True
"""
#####################drf配置#####################
"UNAUTHENTICATED_USER"：属于匿名用户，可以是一个函数引用或者None

"""
REST_FRAMEWORK = {
    "UNAUTHENTICATED_USER": None,
    # token认证
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "ext.auth.QueryParamsAuthentication",
        "ext.auth.HeaderAuthentication",
        "ext.auth.NOAuthentication",
    ],
    # 全局权限
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "ext.per.MyPermission1",
    #     "ext.per.MyPermission2",
    #     "ext.per.MyPermission3",
    # ]
    # 限流配置
    "DEFAULT_THROTTLE_RATES": {
        "ip": "5/m",
        "user": "20/m",
        "vip": "50/m",
    },
    # 版本获取形式
    # QueryParameterVersioning  # 读取get请求参数的version信息
    # URLPathVersioning  # 读取URL路由中的version信息
    # AcceptHeaderVersioning  # 读取请求头中的version信息
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # URL版本参数名
    "VERSION_PARAM": "version",
    # 允许的版本
    "ALLOWED_VERSIONS": ["1.0", "2.0", ],
    # 不传入版本时候的默认版本
    "DEFAULT_VERSION": "1.0",
    # 解析器
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser", ],
    # 根据请求，匹配对应的解析器；寻找渲染器
    "DEFAULT_CONTENT_NEGOTIATION_CLASS": "rest_framework.negotiation.DefaultContentNegotiation",
    # 分页
    # "PAGE_SIZE": 5,
    # 渲染器
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    # 条件搜索
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    # 自动生成API接口文档
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.AutoSchema",

}
