"""
Django settings for CarmiSystem project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$8hqawp4-lctfc)0tlxv807mipv-!umc4!qke%!z8o(8u&6%uy"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    # "django.contrib.auth",
    # "django.contrib.contenttypes",
    # "django.contrib.sessions",
    # "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "web.apps.WebConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "CarmiSystem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",
                # "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "CarmiSystem.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    # myself
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "CarmiSysBases",
        "USER": "root",
        "PASSWORD": "yaung",
        # "HOST": "127.0.0.1",
        "PORT": 3306,
    }
    # VMwareubuntu22.04
    # "default": {
    #     "ENGINE": "django.db.backends.mysql",
    #     "NAME": "CarmiSysBases",
    #     "USER": "root",
    #     "PASSWORD": "root123.",
    #     "HOST": "192.168.70.140",
    #     "PORT": 3306,
    # }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# redis的缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://127.0.0.1:6379",
        "LOCATION": "redis://0.0.0.0:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "yaung"
        }
    }
}

"""
#####################drf配置#####################
"UNAUTHENTICATED_USER"：属于匿名用户，可以是一个函数引用或者None

"""
REST_FRAMEWORK = {
    "UNAUTHENTICATED_USER": None,
    # token认证
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "ext.auth.QueryParamsAuthentication",
        "ext.auth.HeaderAuthentication",
        "ext.auth.NOAuthentication",
    ],
    # 全局权限
    # "DEFAULT_PERMISSION_CLASSES": [
    #     "ext.per.MyPermission1",
    #     "ext.per.MyPermission2",
    #     "ext.per.MyPermission3",
    # ]
    # 限流配置
    "DEFAULT_THROTTLE_RATES": {
        "ip": "5/m",
        "user": "10/m",
        "vip": "15/m",
    },
    # 版本获取形式
    # QueryParameterVersioning  # 读取get请求参数的version信息
    # URLPathVersioning  # 读取URL路由中的version信息
    # AcceptHeaderVersioning  # 读取请求头中的version信息
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    # URL版本参数名
    "VERSION_PARAM": "version",
    # 允许的版本
    "ALLOWED_VERSIONS": ["v1", "v2", ],
    # 不传入版本时候的默认版本
    "DEFAULT_VERSION": "v1",
    # 解析器
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser", ],
    # 根据请求，匹配对应的解析器；寻找渲染器
    "DEFAULT_CONTENT_NEGOTIATION_CLASS": "rest_framework.negotiation.DefaultContentNegotiation",
}
