# Generated by Django 5.0.3 on 2024-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_carmiinfo_carmi_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmiinfo",
            name="carmi_status",
            field=models.IntegerField(
                choices=[(0, "未使用"), (1, "已使用")], default=0, verbose_name="卡密状态"
            ),
        ),
    ]
