# Generated by Django 5.0.3 on 2024-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_carmiinfo_carmi_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmiinfo",
            name="carmi_code",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="卡密码"
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="machine_code",
            field=models.CharField(
                max_length=64, null=True, unique=True, verbose_name="机器码"
            ),
        ),
    ]
