# Generated by Django 5.0.3 on 2024-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_alter_carmiinfo_carmi_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmilog",
            name="using_machine",
            field=models.CharField(max_length=64, null=True, verbose_name="使用机器"),
        ),
    ]
