# Generated by Django 5.0.3 on 2024-03-31 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_carmilog_using_machine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmilog",
            old_name="using_machine",
            new_name="using_user",
        ),
    ]
