# Generated by Django 5.0.3 on 2024-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_rename_using_machine_carmilog_using_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmilog",
            name="using_time",
            field=models.DateTimeField(null=True, verbose_name="使用时间"),
        ),
    ]
