# Generated by Django 5.0.3 on 2024-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_carmilog_using_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmilog",
            name="using_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="使用时间"
            ),
        ),
    ]
