# Generated by Django 5.0.3 on 2024-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_carmilog_using_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmilog",
            name="using_user",
            field=models.CharField(max_length=64, null=True, verbose_name="使用用户"),
        ),
    ]
