# Generated by Django 5.0.3 on 2024-03-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_alter_carmilog_using_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmilog",
            name="using_machine",
            field=models.CharField(max_length=64, null=True, verbose_name="使用机器"),
        ),
        migrations.AlterField(
            model_name="carmilog",
            name="using_user",
            field=models.CharField(max_length=32, null=True, verbose_name="使用用户"),
        ),
    ]
