# Generated by Django 5.0.3 on 2024-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_carmilog_using_machine_alter_carmilog_using_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmilog",
            name="generating_user",
            field=models.CharField(max_length=32, verbose_name="生成用户"),
        ),
    ]
