# Generated by Django 5.0.3 on 2024-04-03 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0011_alter_carmilog_generating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmiinfo",
            name="generating_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 17, 58, 14, 904783),
                verbose_name="生成时间",
            ),
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="generating_user",
            field=models.CharField(default="yy", max_length=32, verbose_name="生成用户"),
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="using_machine",
            field=models.CharField(max_length=64, null=True, verbose_name="使用机器"),
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="using_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="使用时间"
            ),
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="using_user",
            field=models.CharField(max_length=32, null=True, verbose_name="使用用户"),
        ),
        migrations.DeleteModel(
            name="CarmiLog",
        ),
    ]
