# Generated by Django 5.0.3 on 2024-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0014_carmibuylog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarmiBuyLog",
        ),
    ]
