# Generated by Django 5.0.3 on 2024-04-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_delete_carmibuylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarmiBuyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generating_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="购买时间"),
                ),
                (
                    "carmi_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.carmiinfo",
                        verbose_name="卡密",
                    ),
                ),
                (
                    "generating_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.userinfo",
                        verbose_name="购买用户",
                    ),
                ),
            ],
        ),
    ]
