# Generated by Django 5.0.3 on 2024-04-19 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0016_carmibuylog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmibuylog",
            old_name="generating_time",
            new_name="buying_time",
        ),
        migrations.RenameField(
            model_name="carmibuylog",
            old_name="generating_user",
            new_name="buying_user",
        ),
    ]
