# Generated by Django 5.0.3 on 2024-04-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0017_rename_generating_time_carmibuylog_buying_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmiinfo",
            name="carmi_status",
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="carmi_buy_status",
            field=models.IntegerField(
                choices=[(0, "未购买"), (1, "已购买")], default=0, verbose_name="卡密购买状态"
            ),
        ),
        migrations.AddField(
            model_name="carmiinfo",
            name="carmi_use_status",
            field=models.IntegerField(
                choices=[(0, "未使用"), (1, "已使用")], default=0, verbose_name="卡密使用状态"
            ),
        ),
    ]
