# Generated by Django 5.0.3 on 2024-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0020_alter_userinfo_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmiinfo",
            name="carmi_duration",
            field=models.IntegerField(help_text="123123", verbose_name="卡密时长"),
        ),
    ]
