# Generated by Django 5.0.3 on 2024-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_alter_carmiinfo_carmi_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmiinfo",
            name="carmi_duration",
            field=models.IntegerField(verbose_name="卡密时长"),
        ),
    ]
