# Generated by Django 5.0.3 on 2024-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0022_alter_carmiinfo_carmi_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmiuselog",
            name="using_machine",
            field=models.CharField(
                db_index=True, max_length=64, null=True, verbose_name="使用机器"
            ),
        ),
    ]
